apiVersion: extensions/v1beta1                                                                                                                                                      
kind: Deployment                                                                                                                                                                    
metadata:                                                                                                                                                                           
  labels:                                                                                                                                                                           
    run: net-shoot                                                                                                                                                                  
  name: net-shoot                                                                                                                                                                   
spec:                                                                                                                                                                               
  #progressDeadlineSeconds: 600                                                                                                                                                      
  replicas: 1                                                                                                                                                                       
  #revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: net-shoot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: net-shoot
    spec:
      #affinity:
      #  podAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #    - labelSelector:
      #        matchExpressions:
      #        - key: app
      #          operator: In
      #          values:
      #          - smscenter
      #      topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -f
        - /dev/null
        command:
        - tail
        image: datewu/netshoot:latest
        imagePullPolicy: Always
        name: net-shoot
        resources: 
          requests:
            memory: 20Mi
          limits:
            cpu: 40m
            memory: 40Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
